hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 1024
  max_response_length: 1024
  train_batch_size: 256
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_assistant_turns: 5
    sglang_rollout_mode: server
    server:
      timeout: 60
      max_attempts: 3
      retry_delay: 2
      max_connections: 1000
      max_start_wait_time: 300.0