# megatron ref config, inheriting from trainer/config/ref/ref.yaml
defaults:
  - ref

  # megatron engine config
  - ../engine@megatron: megatron
  
  # load the reference default config, then apply the fields in the current yaml
  - _self_

strategy: megatron

megatron:
  _target_: verl.workers.config.MegatronEngineConfig
  seed: ${oc.select:actor_rollout_ref.actor.megatron.seed,42}
  override_transformer_config: ${oc.select:actor_rollout_ref.actor.megatron.override_transformer_config,{}}
  use_mbridge: ${oc.select:actor_rollout_ref.actor.megatron.use_mbridge,False}

load_weight: True